### ISSUE TITLE
[BUG] Form Feed control character causes word to go one line down

### ISSUE THREAD

**Issue by Luhav** [n-ivkovic/tspreed#12]
## Issue:
Form Feed (U+000C) results in the neighbouring word being printed one line too far down (it appears Tspreed is actually processing the FF?)
### Example:
![image](https://user-images.githubusercontent.com/43188089/137158771-010a0446-edcd-4dc0-9334-786d88b5abbe.png)
In this case, the FF was just before 'Organization' - the 'of' that is where it's supposed to be is from a bit later in the file, as the rest of the file keeps reading as normal until it happens across another FF.

## Steps for reproduction:
- have a text file which includes a Form Feed
    - I ended up with such a file by converting [this PDF](https://www.usi.edu/media/3654697/Business-Environment-China.pdf) with pdf2text
- read with Tspreed

## Expected behaviour:
It all stays on the same line, between the tines, instead of writing over the bottom tine.

**Comment by n-ivkovic** [comment]
Thanks for raising this issue. I've rectified in 11194b0 as follows:
* Added the the ability to pass in additional characters to use as word separators in addition to `$IFS`.
* Added the form feed character as an additional word separator in the default config.

This means words will now correctly split on the form feed character once tspreed is installed, or by passing `-s "\f"` to tspreed.

This change should be merged into master and released in the near future, likely in the coming days.
