### ISSUE TITLE
macOs error on make install

### ISSUE THREAD

**Issue by dvogt23** [n-ivkovic/tspreed#2]
Hey pretty nice project! I was in love with https://github.com/olegcherr/Reedy-for-Chrome but not using chrome anymore ... now need to found a solution to get just text from website and paste it to tspeed 👌🏾 should be possible.

BTW

I got an error after `sudo make install `:
```
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

**Comment by n-ivkovic** [comment]
Issue has now been fixed in 1796cb2e13aa27313e3d32829517c63db4c91311. Decided the use of `install` wasn't necessary and only added complication. The commit will likely be merged into master in the coming days.
