### ISSUE TITLE
Focus line not working

### ISSUE THREAD

**Issue by Ilya-Meer** [n-ivkovic/tspreed#5]
Hi, thank you for the awesome tool. I think this is a really convenient utility to have, and I'm getting a lot of use out of the bare presentation of words. However, the focus line option is not working for me. Instead I get an error saying `expr: syntax error`. See screenshot below.

I just ran `sudo make install` without any other modifications. My shell is `zshell` on macOS, which should be supported according to the Readme. Any idea what could be causing this?

**_Edit:_** The default mode works great, but adding the `-f` flag causes this issue since it invokes https://github.com/n-ivkovic/tspreed/blob/16389d1e4f73a5b3774988a63de609937cdb274d/tspreed#L148 which makes use of `expr`

![syntax_error](https://user-images.githubusercontent.com/32082566/101272293-c1debf00-373f-11eb-9813-59e01c5922c4.png)

**Comment by Ilya-Meer** [comment]
I was able to get it working locally by swapping out `expr` for native bash string manipulation. I'd be happy to submit a PR if you like

**Comment by n-ivkovic** [comment]
Thanks for info and the work put into the potential fix. [ShellCheck](https://www.shellcheck.net/) did warn me that `expr` may be antiquated ([SC2003](https://github.com/koalaman/shellcheck/wiki/SC2003)), however I mistakenly thought it would still be well supported.

Please note that this script is intended to be written in POSIX shell, which does not support the Bash string manipulation used in 7a9cbc7953c62370d7749cee5678a999bc436309, see [SC3057](https://github.com/koalaman/shellcheck/wiki/SC3057). I will push a POSIX-compliant fix within the next few days, possibly within the next 24 hours if time permits. I'm happy to merge a PR instead if the changes are POSIX-compliant (i.e. no issues when passed through ShellCheck, I'll make this a requirement for all future PRs)

As a temporary workaround for now you can either continue using your solution or checkout 1796cb2e13aa27313e3d32829517c63db4c91311.

**Comment by Ilya-Meer** [comment]
Ahh, I see, thanks for pointing that out. I didn't realize that my fix wasn't POSIX compliant. I'm not sure that my shell scripting skills are up to the task of cleanly fixing this issue, so I'll use my workaround for now. Thanks again for your reply, I look forward to learning more about POSIX from your future updates :)

**Comment by n-ivkovic** [comment]
The issue has now been fixed in d8bd4e430eca60d9c373d02ea527eda0049acd57. The commit will be merged into master shortly and a new release will be made.
