### ISSUE TITLE
[bug] Local configs made in /root/.config rather than $HOME/.config

### ISSUE THREAD

**Issue by astralchan** [n-ivkovic/tspreed#7]
```
[amber@otaku ~/.local/src/tspreed]$ doas make install
doas (amber@otaku) password:
Installed tspreed in /usr/local/bin/
Created man page /usr/local/share/man/man1/tspreed.1
Created global config /etc/tspreed/tspreed.rc
Created local config directory /root/.config/tspreed/
```
The `install` option will always require root access. Doing so will make the local config in the `/root` home directory rather than the user home directory as intended. Likewise, the `purge` option will attempt to remove from `/root/.config/tspreed` as `purge` will also require root to run.

**Comment by n-ivkovic** [comment]
I've installed `doas` on my Arch machine, specifically community/opendoas 6.6.1-2, and I'm unable to replicate the issue. Could you please provide the following in regards to your machine:
* The version of doas that is currently installed
* The contents of /etc/doas.conf
* A response to the following questions:
  * Does running `doas logname` return root or amber?
  * Does running `doas echo "$USER"` return root or amber?
  * Does running `doas echo "$HOME"` return /root or /home/amber?

**Comment by astralchan** [comment]
The version of doas is `opendoas-6.8_1`
```sh
[amber@otaku ~]$ </etc/doas.conf
permit amber as root
```
```sh
[amber@otaku ~]$ doas logname
doas (amber@otaku) password:
root
```
 ```sh
 [amber@otaku ~]$ doas echo $USER
doas (amber@otaku) password:
amber
```
```sh
[amber@otaku ~]$ doas echo $HOME
doas (amber@otaku) password:
/home/amber
```
As mentioned [here](https://github.com/void-linux/void-packages/pull/27113), a `Makefile` shouldn't ever touch $HOME, especially commands that need root. Apps typically copy configs if it doesn't exist on runtime, not on install. Being a shell script, I might suggest something like this.
```sh
[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/tspreed/tspreedrc ] && mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/tspreed && cp /etc/tspreed/tspreed.rc ${XDG_CONFIG_HOME:-$HOME/.config}/tspreed || source ${XDG_CONFIG_HOME:-$HOME/.config}/tspreed/tspreedrc
```
or however you've defined where the local config file is. It doesn't seem to be a good practice to touch a user's local directories in $HOME via a `Makefile`.

**Comment by n-ivkovic** [comment]
I've installed opendoas 6.8 [from GitHub](https://github.com/Duncaen/OpenDoas/releases/tag/v6.8) on my machine and used an equivalent doas config, yet still received different results from you. I received the same results even when running 6.6.1-2 from the Arch repos.
```
[nick@arcthi]~$ < /etc/doas.conf 
permit nick as root
[nick@arcthi]~$ doas logname
doas (nick@arcthi) password: 
nick
[nick@arcthi]~$ doas echo $USER
doas (nick@arcthi) password: 
nick
[nick@arcthi]~$ doas echo $HOME
doas (nick@arcthi) password: 
/home/nick
```
I'm really scratching my head as to how we could receive different results. I'm in no way knowledgeable enough about how doas or logname works to determine how this happens. I may need read up about these if I wish to figure it out.

As for the idea that Makefiles should not modify files in $HOME, I was not aware of this convention. Is this convention documented anywhere else online, because I have so far been unsuccessful in finding any other mention of it.

**Comment by astralchan** [comment]
I don't know if I necessarily heard it from a specific source, more just from experiences with packages. Install scripts don't seem to make a config in the user home directory until after the first time it's ran.
As for the `doas` issue, I believe it's just a general root permissions oversight.
```sh
[amber@otaku ~/.local/src/tspreed]$ sudo make install
Installed tspreed in /usr/local/bin/
Created man page /usr/local/share/man/man1/tspreed.1
Global config /etc/tspreed/tspreed.rc already exists
Created local config directory /root/.config/tspreed/
```
Same thing happens with `sudo`.
```sh
[amber@otaku ~/.local/src/tspreed]$ sudo logname
root
[amber@otaku ~/.local/src/tspreed]$ sudo echo $USER
amber
[amber@otaku ~/.local/src/tspreed]$ sudo echo $HOME
/home/amber
```
`sudo` version 1.9.4_1.

**Comment by paper42** [comment]
@kawaiiamber setting keepenv in doas.conf may help.

> As for the idea that Makefiles should not modify files in $HOME, I was not aware of this convention. Is this convention documented anywhere else online, because I have so far been unsuccessful in finding any other mention of it.

It's probably not written anywhere, this is the first project which tries to do this. Usually make install is used for a system-wide installation, so there is no reason to install something to user's $HOME. I usually see projects install a global config file or a sample config (and warning the user until they copy the sample config to the correct location). Using $HOME is, as you can see, problematic.

**Comment by n-ivkovic** [comment]
I understand your reasoning now. Files in the user's $HOME will no longer be touched 87bad7df149708255e9cc6f5a40902ad4f4b803f
